### ISSUE TITLE
Please change the script tag in the index file

### ISSUE THREAD

**Issue by adarsh1021** [Swarupa567/swarupap.github.io#2]
https://github.com/Swarupa567/swarupap.github.io/blob/b2e1fc6b63fb7840ccd08539c8df7685c5bcb903/index.html#L403

Hi, looks like you have used my portfolio website as a reference for building your own. 

Can you please remove all the javascript from the script tag and then use it ? I have used it for people to sign up to my newsletter using Firebase, and there is API details associated. 

I think it would be better if you use the original template here, than the version I created. 
I found it here - https://github.com/BlackrockDigital/startbootstrap-resume

Thanks

**Comment by Swarupa567** [comment]
Sure Adarsh, I will use the original template
